name: Deploy to Surge

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    
    - run: npm install -g surge
    - run: surge ./ ${{ secrets.apromaster-github-page.surge.sh }} --token ${{ secrets.88eead54ea33f15e358ede371bb6cf9c }}

    